// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAboeOUHI0eMQPLcpwngHDbHQWF_eRZZPw',
    appId: '1:202888499185:web:de8b669b725aec0a837e50',
    messagingSenderId: '202888499185',
    projectId: 'wham-ad61b',
    authDomain: 'wham-ad61b.firebaseapp.com',
    storageBucket: 'wham-ad61b.appspot.com',
    measurementId: 'G-8JQZFE7FF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-Gq2YdV8E82qv2aDSKrsWJgurOsT6FbI',
    appId: '1:202888499185:android:82d55d594a3baa26837e50',
    messagingSenderId: '202888499185',
    projectId: 'wham-ad61b',
    storageBucket: 'wham-ad61b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw3rlf9XPYonNuo7ZpABNq2fjcfTPvWg4',
    appId: '1:202888499185:ios:07bf0d4bca473e65837e50',
    messagingSenderId: '202888499185',
    projectId: 'wham-ad61b',
    storageBucket: 'wham-ad61b.appspot.com',
    androidClientId: '202888499185-b9q6l6icl4fd63hp455gnec0lm5igbt0.apps.googleusercontent.com',
    iosClientId: '202888499185-0gb3rgla3iog2khir32fumso874e9o50.apps.googleusercontent.com',
    iosBundleId: 'com.example.wham',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw3rlf9XPYonNuo7ZpABNq2fjcfTPvWg4',
    appId: '1:202888499185:ios:07bf0d4bca473e65837e50',
    messagingSenderId: '202888499185',
    projectId: 'wham-ad61b',
    storageBucket: 'wham-ad61b.appspot.com',
    androidClientId: '202888499185-b9q6l6icl4fd63hp455gnec0lm5igbt0.apps.googleusercontent.com',
    iosClientId: '202888499185-0gb3rgla3iog2khir32fumso874e9o50.apps.googleusercontent.com',
    iosBundleId: 'com.example.wham',
  );
}
